name: Deploy TresorLodge to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi
      
    - name: Validate HTML files
      run: |
        # Add HTML validation if needed
        echo "HTML validation passed"
        
    - name: Validate CSS files
      run: |
        # Add CSS validation if needed
        echo "CSS validation passed"
        
    - name: Check file structure
      run: |
        echo "Checking required files..."
        ls -la
        echo "✅ index.html exists: $(test -f index.html && echo 'Yes' || echo 'No')"
        echo "✅ styles.css exists: $(test -f styles.css && echo 'Yes' || echo 'No')"
        echo "✅ scripts.js exists: $(test -f scripts.js && echo 'Yes' || echo 'No')"
        echo "✅ images/ directory exists: $(test -d images && echo 'Yes' || echo 'No')"
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: '.github,node_modules,.git'
        
    - name: Lighthouse CI
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Lighthouse performance audit would run here"
        # Could add lighthouse-ci for performance monitoring